-- ============================================================================
-- ONE-TIME DATA IMPORT — Base44 production export -> Supabase
-- Generated by supabase/data-import/build_import_sql.py — do not hand-edit;
-- re-run the generator against a fresh export instead.
--
-- This is NOT a schema migration (nothing here touches table structure) and
-- is meant to run exactly once, after supabase/migrations/0015 has been
-- applied. It REPLACES the current contents of the 15 tables listed below
-- with the Base44 export, per an explicit choice to make Supabase's data
-- match that export exactly rather than merge with whatever is there now.
--
-- WARNING - read before running:
--  * This deletes ALL current rows in: gap_updates, gaps, recurring_overrides, recurring_events, task_completions, direct_tasks, events, daily_summaries, daily_routines, warehouse_items, withdrawal_requests, equipment_holdings, equipment_settings, constraints, access_requests.
--  * Deleting `events` cascades to `event_contacts` and `event_confirmations`
--    (0004_event_contacts_confirmations.sql) for any of THOSE rows that
--    point at an event being deleted — Base44 never had that feature, so
--    this export can't restore them. If real confirmation/contact data
--    already exists in Supabase for current events, back it up first.
--  * Every imported row is attributed to created_by_id = '6292bb9d-89e3-4054-a822-38960eeafa16'
--    (must already exist in auth.users — checked below before anything runs).
--  * All ids are freshly generated (Base44's own ids aren't valid Postgres
--    uuids) via uuid5, deterministically from each row's original Base44 id —
--    re-running this generator against the same export reproduces the same
--    ids, so gaps<->gap_updates and recurring_events<->recurring_overrides
--    cross-references stay correct, and so does task_completions.task_id
--    (remapped to the new events/direct_tasks/daily_routines id it points at).
-- ============================================================================
--
-- Rows dropped from this export (orphaned foreign keys - see comment on each):
-- Skipped gap_updates id=6ab384c8a9f69d61c85d002d: its gap_id 6aa6c84101f548a11893aeda does not exist in the Gap export (that gap was presumably deleted in Base44 after this update-log entry was written).
-- ----------------------------------------------------------------------------

begin;

-- Preflight 1: the attribution account must be a real auth user.
do $$
begin
  if not exists (select 1 from auth.users where id = '6292bb9d-89e3-4054-a822-38960eeafa16') then
    raise exception 'Import aborted: created_by_id 6292bb9d-89e3-4054-a822-38960eeafa16 not found in auth.users. Update IMPORT_USER_ID in build_import_sql.py and regenerate, or create that user first.';
  end if;
end $$;

-- Preflight 2: 0015_task_completions_direct_type.sql must already be applied
-- (this export contains task_type = 'direct' rows the old CHECK constraint rejects).
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'task_completions_task_type_check'
      and pg_get_constraintdef(oid) like '%direct%'
  ) then
    raise exception 'Import aborted: run supabase/migrations/0015_task_completions_direct_type.sql first.';
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- Wipe (children before parents)
-- ---------------------------------------------------------------------------
delete from public.gap_updates;
delete from public.gaps;
delete from public.recurring_overrides;
delete from public.recurring_events;
delete from public.task_completions;
delete from public.direct_tasks;
delete from public.events;
delete from public.daily_summaries;
delete from public.daily_routines;
delete from public.warehouse_items;
delete from public.withdrawal_requests;
delete from public.equipment_holdings;
delete from public.equipment_settings;
delete from public.constraints;
delete from public.access_requests;

-- ---------------------------------------------------------------------------
-- Insert (parents before children)
-- ---------------------------------------------------------------------------
insert into public.gaps (id, company, gap, location, class_name, building_number, room_number, status, priority, note, reporter_name, reporter_phone, attachments, created_by, created_by_id, created_date, updated_date) values
  ('4521faf6-fa15-5128-a0c4-0b500425d6f1', 'תמר', 'התקנת לוח שעם בכיתה פלוגתית (5)', 'כיתות', 'כיתת פלוגת תמר, 5', null, null, 'בטיפול', 'בינוני', null, 'זיו שמיר', '0539190969', '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-27T08:04:55.545000'::timestamptz, '2026-09-27T08:04:55.545000'::timestamptz),
  ('1fd27232-c31f-5040-8922-92994f536298', 'תמר', 'התקנת וילון בחדר 207', null, null, null, null, 'בטיפול', 'גבוה', 'תקלה מוכרת כבר מימי הקליטה', 'זיו שמיר', '0539190969', '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-27T06:25:41.294000'::timestamptz, '2026-09-27T08:05:04.702000'::timestamptz),
  ('26e3e1e2-18f5-594e-b5aa-c20e03cba750', 'בשור', 'התפוצץ צינור במכונת כביסה של הבנים בקומה 2 במגורים הכל משפריץ לכל מקום בשירותים', 'מגורי בנים', null, null, null, 'בטיפול', 'קריטי', null, 'נועם כהן', '0528697225', '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-24T10:52:08.378000'::timestamptz, '2026-09-24T12:04:14.729000'::timestamptz),
  ('18beb3e0-fed8-5c72-a28d-d8e6fe1d2d58', 'צין', 'נזילה בשירותי בנות - מתחם קמנים', 'מתחם קמנים', null, null, null, 'בטיפול', 'קריטי', null, null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-23T10:12:18.940000'::timestamptz, '2026-09-23T10:24:00.988000'::timestamptz),
  ('1c626635-b019-58fd-b9f0-01c8881eda7b', 'רמון', 'במגורים שנקראים תעלה, איפה שקקס ישנים יש לנו גם חברה, בחדר 7 הידית שבורה ואפשר להינעל במפנים.', 'כניסה למגורי בנים', null, 'אין', '7', 'בטיפול', 'גבוה', 'הלוואי והייתי יודע איפה זה בדיוק, אבל זה נשמע חשוב', 'אלעזר', '''+972 50-300-0930', '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-23T09:50:24.751000'::timestamptz, '2026-09-23T10:23:23.497000'::timestamptz),
  ('3a7c1253-7d87-5628-b12f-6e8db5190291', 'פארן', 'שירותי בבנות - תא שלישי משמאל סתום , תא רביעי משמאל שבור', null, null, null, null, 'טופל', 'נמוך', 'תוקן', null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-23T07:49:11.632000'::timestamptz, '2026-09-23T07:49:28.971000'::timestamptz),
  ('1de6a54b-1454-589f-ae91-6d22d4ec4451', 'צין', 'אסלה שבורה - מגורי בנים בניין 78 
שירותי בנים קומה ראשונה', null, null, null, null, 'בטיפול', 'גבוה', null, null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-23T07:32:43.122000'::timestamptz, '2026-09-23T10:19:06.812000'::timestamptz),
  ('24e97f7b-a8c1-5bb1-a9f7-361ba11d214b', 'פארן', 'דלת לא נסגרת בחדר', 'מגורי בנים', null, null, '202', 'בטיפול', 'בינוני', 'חדר 202', 'עידן פיפאנו', '''‪+972 54‑945‑1127‬', '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-22T20:13:37.788000'::timestamptz, '2026-09-23T10:15:27.214000'::timestamptz),
  ('4fb91721-6b67-5a32-895c-92e00eff9e99', 'צין', 'דלת לא תקינה צילינדר שבור', 'מתחם קמנים חיצוני', null, null, null, 'בטיפול', 'גבוה', 'כיתה 37 בניין מודש', null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-22T19:03:01.979000'::timestamptz, '2026-09-23T10:17:56.260000'::timestamptz),
  ('b48a580d-0e5f-50d8-8828-85f69f5d6a4e', 'בשור', 'וילון תקול ולא יורד בחדר 209', 'מגורי בנים', null, null, '209', 'בטיפול', 'בינוני', null, 'נועם כהן', '0528697225', '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-22T19:00:56.460000'::timestamptz, '2026-09-23T10:25:51.262000'::timestamptz),
  ('b83442a0-3725-5b75-843c-46304f5c4e18', 'פארן', 'מזגן ללא תריס (תריס שבור)', 'מגורי בנות', null, null, null, 'בטיפול', 'נמוך', 'אין תריס למזגן בחדר 202', null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-15T07:36:47.197000'::timestamptz, '2026-09-16T09:32:43.410000'::timestamptz),
  ('775137a5-ff5f-5185-92ec-6b2bcfff2c0e', 'בשור', 'כיתת לינוי הדלת נעולה ולא נפתחת מנעול תקול הכיתה נמצאת אחרי השק״מ', 'מתחם קמנים חיצוני', null, null, null, 'טופל', 'קריטי', null, null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T20:50:53.618000'::timestamptz, '2026-09-17T12:02:55.068000'::timestamptz),
  ('57e66ab8-b380-5655-8431-0304a89e4be3', 'בשור', 'מנורה מעל השירותי בנות תקולה בקומה הראשונה', 'מגורי בנות', null, null, null, 'טופל', 'גבוה', null, null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T15:51:26.137000'::timestamptz, '2026-09-22T18:33:46.160000'::timestamptz),
  ('3c56a4ea-336e-5e2b-a03c-42810336336d', 'צין', 'מזגן לא עובד - השנייה בבניין תבור כיתה 55 (צוות עופר) - יחזרו לתקן', null, null, null, null, 'בטיפול', 'גבוה', 'כיתת למדן', null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T15:13:57.101000'::timestamptz, '2026-09-22T07:49:09.283000'::timestamptz),
  ('4a696aa6-85a7-56c7-ba73-b29bab9da6f5', 'צין', 'מזגן לא עובד - במבנה 26 כיתה 19 (צוות גילי)', null, null, null, null, 'טופל', 'גבוה', 'כיתות למדן', null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T15:13:21.727000'::timestamptz, '2026-09-22T07:48:54.814000'::timestamptz),
  ('cef5eea7-d61e-5973-9587-84bc9e9226ea', 'פארן', 'חדר 109 כל השקעים לא מחזיקים מטען כמעט', 'מגורי בנים', null, null, null, 'טופל', 'בינוני', null, null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T21:02:17.383000'::timestamptz, '2026-09-17T12:11:06.180000'::timestamptz),
  ('8e81090c-60ac-5227-a884-372618b777ac', 'רמון', 'התפוצץ צינור בשירותים', 'מגורי בנים', null, null, null, 'בטיפול', 'קריטי', 'קומה שנייה', null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-16T12:45:11.679000'::timestamptz),
  ('b9eb5b7d-dbf3-5ae8-9688-1863f21b9109', 'רמון', 'מזגן תקול', 'מגורי בנים', null, null, null, 'טופל', 'בינוני', 'המזגן ב205 לא מקרר', null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-17T12:00:22.535000'::timestamptz),
  ('cc0fe401-0d6a-5596-a143-f467208708ff', 'רמון', 'גלאי עשן', 'מגורי בנים', null, null, null, 'טופל', 'בינוני', 'בחדר 203 הגלאי לא מתוקן על התקרה', null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-20T06:55:22.807000'::timestamptz),
  ('b2cc1193-33f5-54ee-88fb-795bab39e07f', 'צין', 'שקע רופף', 'מגורי בנים', null, null, null, 'טופל', 'גבוה', 'חדר 211', null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-17T12:08:06.254000'::timestamptz),
  ('cc0cac6a-92bd-5239-b855-811c62e38f3d', 'בשור', 'חדר 210 - ארון שבור + תיקון וילון', 'מגורי בנים', null, null, null, 'בטיפול', 'נמוך', null, null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-16T09:33:34.427000'::timestamptz),
  ('1fe7c822-aa45-5495-a2ef-a7fc32b0a715', 'בשור', 'חדר 211 וילון חדש', 'מגורי בנות', null, null, null, 'בטיפול', 'נמוך', null, null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-16T09:34:11.914000'::timestamptz),
  ('0f56c7a4-d4de-59ed-944e-5e5a3f57553f', 'בשור', 'חדר 211 דלת לא נסגרת', 'מגורי בנות', null, null, null, 'טופל', 'גבוה', null, null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-14T15:44:18.735000'::timestamptz),
  ('8dfcf6a6-465f-507c-8571-0ba27680fb3f', 'בשור', 'חדר 201 - מזגן עובד חלש', 'מגורי בנות', null, null, null, 'טופל', 'בינוני', null, null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-20T07:44:22.702000'::timestamptz),
  ('1a8611b4-96c9-5e74-99a3-00e29cee0d56', 'פארן', 'שירותי בנות תקולים', 'מגורי בנות', null, null, null, 'בטיפול', 'גבוה', 'קומה עליונה: 
תא שני משמאל שבור', null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-23T10:32:36.571000'::timestamptz),
  ('aa0627a3-b264-5db5-8b55-67e2a45e1611', 'פארן', 'הקולר במגורי קמנים שהוא החלק הגבוה', 'מגורי בנים', null, null, null, 'טופל', 'בינוני', null, null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-14T20:31:56.761000'::timestamptz),
  ('acc0dfa0-276a-55ed-be24-59490dcdd004', 'תמר', 'הוספת שקעים', 'מגורי בנות', null, null, null, 'טופל', 'גבוה', 'מקרר לצליאקית- 7 שקעים בחדר של 8 בנות, יש להוסיף שקעים', null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-23T10:31:50.630000'::timestamptz),
  ('134cd82a-4b83-525b-982b-cad74a7b3bc9', 'צין', 'שקע לא תקין', 'מגורי בנים', null, null, null, 'טופל', 'גבוה', 'חדר 211', null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-17T12:57:28.815000'::timestamptz),
  ('c3130dbb-ecdb-56b2-a52e-54951502caed', 'רמון', 'מזגן תקול', 'מגורי בנים', null, null, null, 'בטיפול', 'בינוני', 'היה איש מקצוע ולא הצליח לתקן. הוא יחזור שוב.', null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-13T15:58:57.187000'::timestamptz),
  ('62c04718-0c2e-5d02-9dda-404b71f6d2dc', 'פארן', 'דלת של הכיתה הפלוגתית לא נסגרת', 'מתחם קמנים חיצוני', null, null, null, 'טופל', 'בינוני', 'פער רציני מבחינת במ כי הדלת נפתחת כל הזמן', null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-22T07:02:09.598000'::timestamptz),
  ('9a997344-db1a-5044-bd14-52ad817c1a08', 'בשור', 'התמי 4 לא תקין', 'מתחם קמנים חיצוני', null, null, null, 'בטיפול', 'גבוה', 'המים הקרים לא עובדים', null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-13T15:59:24.345000'::timestamptz),
  ('267ffebe-5e7e-5ebf-9f5c-a9aae7af0b7a', 'צין', 'סתימה שירותי בנות', 'מתחם קמנים חיצוני', null, null, null, 'בטיפול', 'קריטי', 'התא הימני ביותר', null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-17T06:37:10.038000'::timestamptz),
  ('6c435c36-f186-5709-8187-dd80bf840763', 'רמון', 'מזגן בחדר 107', 'מגורי בנות', null, null, null, 'בטיפול', 'בינוני', 'ניסו להוריד את המעלות, אבל המזגן עדיין לא מקרר בכלל, כנראה צריך לתקן', null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-13T15:58:57.187000'::timestamptz),
  ('e3091f5d-682e-5058-bfe9-1dc58fd2a556', 'רמון', 'חדר עם מזגן תקול', 'מגורי בנים', null, null, null, 'בטיפול', 'בינוני', 'חדר 204 מאמינים שהמזגן מלוכלך מבפנים', null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-13T15:58:57.187000'::timestamptz),
  ('45437956-2e2e-52e7-93a6-c2e44a0748e9', 'פארן', 'חדרים עם עובש לא תקינים', 'מגורי בנים', null, null, null, 'בטיפול', 'בינוני', 'חדר 111 ועוד', null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-13T15:58:57.187000'::timestamptz),
  ('5225d8a8-74c3-54e4-91f2-82ebc97f2c31', 'פארן', 'סתימה בתא 1 מימין', 'מגורי בנות', null, null, null, 'בטיפול', 'קריטי', null, null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-16T12:45:46.030000'::timestamptz),
  ('52dbc117-291e-5d1d-98b7-82871d4c00f0', 'פארן', 'עמדת גלחצ בלי מברשת וגלחצ', 'מתחם קמנים חיצוני', null, null, null, 'טופל', 'בינוני', null, null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-15T07:35:54.070000'::timestamptz),
  ('345083d0-2c34-5f4f-8f7c-f9d4fa109551', 'פארן', 'גלילי נייר וציוד ניקיון מגורים כלליים', 'מגורי בנים', null, null, null, 'טופל', 'בינוני', 'גם בנים וגם בנות', null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-13T15:58:57.187000'::timestamptz),
  ('13e97c3d-dd7c-5972-a244-d94215122e57', 'פארן', 'גלאי בלי סוללות תקינות', 'מגורי בנות', null, null, null, 'טופל', 'בינוני', 'חדר 204', null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-14T20:28:40.837000'::timestamptz),
  ('fe164f5f-40bc-5cb0-ac6a-f366c258367f', 'פארן', 'רצפה תקולה בכניסה', 'מגורי בנות', null, null, null, 'בטיפול', 'גבוה', null, null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-17T06:47:28.306000'::timestamptz),
  ('aed9dd82-aaf5-5587-855f-1cdb79b50602', 'בשור', 'קולר לא תקין', 'דקצו', null, null, null, 'בטיפול', 'גבוה', 'צריך להטות אותו בשביל מים', null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-16T12:45:56.374000'::timestamptz),
  ('22108fa6-f7b6-5535-96ca-37fda661988b', 'פארן', 'מנורה תקולה בפינת פריסה', 'מתחם קמנים חיצוני', null, null, null, 'טופל', 'בינוני', null, null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-17T11:51:00.886000'::timestamptz),
  ('a6530efa-46f9-5703-b1a8-a5ed903fd805', 'פארן', 'שירותים תקולים - אסלה מפורקת במבנה בנים קומה ראשונה', 'מגורי בנים', null, null, null, 'טופל', 'גבוה', null, null, null, '[]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T15:58:57.187000'::timestamptz, '2026-09-23T07:31:18.312000'::timestamptz);

insert into public.recurring_events (id, title, start_time, end_time, recurrence, pluga, details, created_by, created_by_id, created_date, updated_date) values
  ('f31e5810-88cf-56de-90fc-4f188bbeab2e', 'תיאום הסעים ומזון לסיורים השבוע', '08:00', '09:00', 'sunday', 'רמון', 'בדיקת כלל הסיורים לשבוע הקרוב ולקבוע אוטובוסים, קיבוץ עינת, ונשנושים לסיורים ואירועים חיצוניים לבסיס.', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T19:02:04.723000'::timestamptz, '2026-09-14T19:02:04.723000'::timestamptz),
  ('2c792b9f-4c21-572f-8843-72557e92dc66', 'שליחת פלייבוקס לחוסרים במחסן', '08:00', '09:00', 'wednesday', 'תמר', 'מיפוי כל שבוע לכלל החוסרים והזמנה ביום רביעי. יום ראשון לוודא שהגיעה ההזמנה.', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T19:00:34.371000'::timestamptz, '2026-09-14T19:00:34.371000'::timestamptz);

insert into public.direct_tasks (id, title, pluga, responsible_plugas, task_date, start_time, end_time, status, notes, created_by, created_by_id, created_date, updated_date) values
  ('ddda45cd-901d-5b06-a5ad-dd8919dd4c37', 'להשיג מתנדב מכל פלוגה למחר ב8:00', null, array['פארן','בשור','צין','רמון','תמר']::text[], '2026-09-15', null, null, 'טופלה', null, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-15T12:56:44.652000'::timestamptz, '2026-09-15T15:34:36.971000'::timestamptz),
  ('ed4a6ab6-3fda-5392-a630-359adeefe564', 'משימה לדוגמה', 'בשור', '{}'::text[], '2026-09-14', '10:00', '11:00', 'פתוחה', null, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T20:35:42.803000'::timestamptz, '2026-09-14T20:35:42.803000'::timestamptz),
  ('4b8dbf6a-c307-5e66-a1f6-cd1a77c70106', 'משיכת קסדות הגנש', null, array['פארן','בשור','תמר','רמון']::text[], '2026-09-16', null, null, 'טופלה', 'שעה תעודכן בהמשך. כלל הפלוגה צריכה להיות נוכחה.', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T18:48:46.550000'::timestamptz, '2026-09-16T15:26:28.969000'::timestamptz),
  ('5fa85518-4555-59c9-baa6-ecf98c39c6b0', 'משיכת קסדות להגנש', null, array['פארן','בשור','רמון','תמר']::text[], '2026-09-14', null, null, 'טופלה', 'רמון + תמר 13:00-13:30
פארן + בשור 19:00-19:30', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T18:14:51.098000'::timestamptz, '2026-09-14T18:48:11.231000'::timestamptz);

insert into public.events (id, event_type, event_date, start_time, end_time, title, details, transport_pluga, transport_details, food_pluga, food_details, responsible_plugas, created_by, created_by_id, created_date, updated_date) values
  ('17f1658b-00f6-596a-a2fa-e91fca8ef4b0', 'פנימי', '2026-09-27', '18:45', '19:15', 'זיכוי הגנש', null, null, null, null, null, array['פארן']::text[], 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-27T08:46:54.150000'::timestamptz, '2026-09-27T08:46:54.150000'::timestamptz),
  ('578827d6-49c1-59eb-a950-35de9123bcc0', 'פנימי', '2026-09-27', '18:00', '18:40', 'זיכוי הגנש', null, null, null, null, null, array['רמון']::text[], 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-27T08:46:32.438000'::timestamptz, '2026-09-27T08:46:32.438000'::timestamptz),
  ('37cc2bad-c811-5b7e-8a40-875c379bd16a', 'פנימי', '2026-09-27', '13:00', '13:30', 'זיכוי הגנש', null, null, null, null, null, array['בשור']::text[], 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-27T08:46:06.158000'::timestamptz, '2026-09-27T08:46:06.158000'::timestamptz),
  ('486b9c63-d49d-525c-9903-47e4a8edcdac', 'פנימי', '2026-09-27', '12:30', '13:00', 'זיכוי הגנש', null, null, null, null, null, array['תמר']::text[], 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-27T08:45:37.138000'::timestamptz, '2026-09-27T08:45:37.138000'::timestamptz),
  ('a4284649-dddb-58f7-a73f-20b3821732f9', 'פנימי', '2026-09-16', '16:45', '17:00', 'משיכת קסדות', 'רק שומרון', null, null, null, null, array['רמון']::text[], 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-16T10:04:26.949000'::timestamptz, '2026-09-16T11:57:46.274000'::timestamptz),
  ('3237caa2-8fd0-5a1e-87a9-44ad903b8bf2', 'פנימי', '2026-09-16', '16:10', '16:30', 'משיכת קסדות', null, null, null, null, null, array['פארן']::text[], 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-16T10:04:08.933000'::timestamptz, '2026-09-16T10:04:08.933000'::timestamptz),
  ('9cf7e17a-60c7-5d9a-86db-5f8c416f92f5', 'פנימי', '2026-09-16', '16:30', '16:45', 'משיכת קסדות', null, null, null, null, null, array['בשור']::text[], 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-16T10:03:24.317000'::timestamptz, '2026-09-16T11:57:08.243000'::timestamptz),
  ('0c6a6deb-7faf-5de0-9932-c14f9d861fa2', 'פנימי', '2026-09-16', '19:00', '19:15', 'משיכת קסדות', null, null, null, null, null, array['תמר']::text[], 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-16T10:02:41.359000'::timestamptz, '2026-09-16T11:56:50.450000'::timestamptz),
  ('6e12b63c-58e9-57f3-95a4-a47406e5628c', 'פנימי', '2026-09-16', '13:30', '17:00', 'הכנות להגנש', null, null, null, null, null, array['תמר','רמון','בשור','פארן','צין']::text[], 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T17:05:41.361000'::timestamptz, '2026-09-13T17:05:41.361000'::timestamptz),
  ('ab4d07be-fbad-532e-ae3d-9850f1415ebc', 'חיצוני', '2026-09-15', '19:00', '02:00', 'סיור סליחות', 'סיור סליחות כולל נסיעה לירושלים, הרצאה, סיור ומשבצת מפקד והגעה לכותל - סליחות למי שישאר (סליחות מתחיל ב-00:15 ונגמר בסביבות 2:00', 'רמון', null, 'רמון', null, '{}'::text[], 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T17:04:35.840000'::timestamptz, '2026-09-14T18:48:00.368000'::timestamptz);

insert into public.daily_summaries (id, summary_date, entries, created_by, created_by_id, created_date, updated_date) values
  ('47af6f39-02ad-53e8-a078-648dfc8c81e2', '2026-09-10', '[{"areas": ["מגורי בנים"], "pluga": null, "notes": "חדר 101 תקול\nלא העמידו טוב את חדר 111\nחדר 200 עם עובש"}, {"areas": ["מגורי בנות"], "pluga": null, "notes": "שירותים לא עמדו "}, {"areas": ["דקצו"], "pluga": null, "notes": "מלא לכלוך סתם זרוק בכל מקום "}]'::jsonb, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-10T13:00:53.043000'::timestamptz, '2026-09-10T13:00:53.043000'::timestamptz);

insert into public.daily_routines (id, routine_date, morning_assembly_plugas, frisa_morning, noon_cleaning, evening_cleaning, created_by, created_by_id, created_date, updated_date) values
  ('0d2cc6ef-eb11-56f7-a9c6-990c0b0d1ebf', '2026-09-27', array['תמר']::text[], 'תמר', 'תמר', 'תמר', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-25T08:10:18.133000'::timestamptz, '2026-09-25T08:10:26.936000'::timestamptz),
  ('7f463b60-446b-53dd-8802-a8e2dd56a2a1', '2026-10-01', array['רמון','צין','בשור','תמר','פארן']::text[], 'רמון', 'צין', 'פארן', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-23T17:45:32.565000'::timestamptz, '2026-09-23T17:46:04.753000'::timestamptz),
  ('d3f48990-5b96-5d12-b3bd-26fdf0d3324e', '2026-10-01', array['תמר']::text[], 'טרם הוחלט', 'טרם הוחלט', 'טרם הוחלט', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-23T17:45:32.359000'::timestamptz, '2026-09-23T17:45:32.359000'::timestamptz),
  ('40af6f25-0429-5245-a678-46fb60619f52', '2026-09-30', array['צין','תמר']::text[], 'צין', 'תמר', 'תמר', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-23T17:45:12.337000'::timestamptz, '2026-09-23T17:45:18.699000'::timestamptz),
  ('bafa7db3-5004-5b90-9b2e-d905fdf755ad', '2026-09-29', array['בשור','פארן']::text[], 'פארן', 'בשור', 'בשור', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-23T17:44:51.617000'::timestamptz, '2026-09-23T17:44:59.273000'::timestamptz),
  ('cc79b49c-013c-5bd9-bb80-48e5c01717b8', '2026-09-28', array['רמון']::text[], 'רמון', 'רמון', 'רמון', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-23T17:44:35.970000'::timestamptz, '2026-09-23T17:44:42.009000'::timestamptz),
  ('41031b7a-a125-5f55-9e46-f858d1e54ffc', '2026-09-24', array['צין']::text[], 'צין', 'צין', 'צין', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-23T17:39:38.398000'::timestamptz, '2026-09-23T17:39:55.338000'::timestamptz),
  ('bfed72bc-931d-5519-9c63-53ee16fd6d59', '2026-09-17', array['בשור','רמון']::text[], 'טרם הוחלט', 'טרם הוחלט', 'טרם הוחלט', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-16T17:27:31.571000'::timestamptz, '2026-09-16T17:27:32.068000'::timestamptz),
  ('fbda381b-d31e-5645-9b83-52c20b7adf79', '2026-09-17', array['פארן','צין','תמר','בשור','רמון']::text[], 'טרם הוחלט', 'טרם הוחלט', 'טרם הוחלט', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-16T17:27:31.368000'::timestamptz, '2026-09-16T17:27:35.416000'::timestamptz),
  ('14a3d0fb-fd89-5729-b7d3-04c80d413c7f', '2026-09-16', array['צין']::text[], 'תמר', 'תמר', 'תמר', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-15T13:50:04.839000'::timestamptz, '2026-09-16T13:17:33.992000'::timestamptz),
  ('1efe47f3-8e97-51d4-a43a-e170d51a4728', '2026-09-15', array['בשור','פארן']::text[], 'צין', 'פארן', 'פארן', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T14:12:17.089000'::timestamptz, '2026-09-15T16:43:08.001000'::timestamptz),
  ('ddf662b3-c50a-58ce-b453-5255a099bb8c', '2026-09-14', array['רמון']::text[], 'רמון', 'רמון', 'רמון', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T16:47:14.638000'::timestamptz, '2026-09-13T16:53:24.225000'::timestamptz),
  ('978b8298-535c-51ab-9a04-40858e0c9405', '2026-09-13', array['פארן','בשור']::text[], 'פארן', 'רמון', 'רמון', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T08:32:34.312000'::timestamptz, '2026-09-13T20:42:31.496000'::timestamptz),
  ('f4181ab3-5e94-547c-b72e-622c8e42fc3d', '2026-09-12', '{}'::text[], 'טרם הוחלט', 'טרם הוחלט', 'טרם הוחלט', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-11T21:19:42.376000'::timestamptz, '2026-09-11T21:19:43.431000'::timestamptz),
  ('e3b89f3b-dc18-54c6-af8e-711adaf19ca9', '2026-09-11', '{}'::text[], 'צין', 'רמון', 'רמון', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-11T18:12:51.646000'::timestamptz, '2026-09-11T19:49:01.579000'::timestamptz),
  ('fe60d68d-0eb7-5d8b-8fa8-cf370e54a367', '2026-09-10', '{}'::text[], 'בשור', 'צין', 'תמר', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-10T12:49:20.263000'::timestamptz, '2026-09-10T13:20:49.784000'::timestamptz);

insert into public.warehouse_items (id, warehouse, name, quantity, returnable, created_by, created_by_id, created_date, updated_date) values
  ('ccd9490a-f9dd-50ab-a83f-e3ada505fecb', 'מכולה', 'גריקן', 15, true, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T19:40:54.114000'::timestamptz, '2026-09-14T20:39:31.844000'::timestamptz),
  ('73a15907-f18f-5f69-b573-8c7c756731af', 'מכולה', 'פויקה', 2, true, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T19:40:45.125000'::timestamptz, '2026-09-14T19:40:45.125000'::timestamptz),
  ('0afc34e0-8fcd-5de9-993d-16a99030d180', 'מכולה', 'מחבטים', 2, true, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T19:40:37.700000'::timestamptz, '2026-09-14T20:39:34.544000'::timestamptz),
  ('242e8c03-6e48-5360-8c2f-e71523d1267a', 'מכולה', 'מטף', 2, true, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T19:40:30.711000'::timestamptz, '2026-09-14T20:39:37.011000'::timestamptz),
  ('044df9e5-c97c-5167-a925-4f1e766072f4', 'מכולה', 'תרמוקן', 4, true, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T19:40:20.191000'::timestamptz, '2026-09-14T19:40:20.191000'::timestamptz),
  ('8087e81f-9132-5047-8bd5-5027b4ac7bd6', 'מכולה', 'חופיות', 4, true, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T19:40:11.193000'::timestamptz, '2026-09-14T19:40:11.193000'::timestamptz),
  ('784d93f8-d888-5924-b697-15e9eb5e1463', 'מכולה', 'שולחן', 6, true, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T19:40:04.754000'::timestamptz, '2026-09-14T19:40:04.754000'::timestamptz),
  ('7f24ac56-3e49-5de5-b521-9f1d6c410ecc', 'מכולה', 'ארגז עץ', 1, true, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T19:39:50.138000'::timestamptz, '2026-09-14T19:39:50.138000'::timestamptz),
  ('05b8bad5-177e-5840-b586-7faabad94167', 'מכולה', 'ארגז סמל', 3, true, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T19:39:39.743000'::timestamptz, '2026-09-14T19:39:39.743000'::timestamptz),
  ('fd8465c5-e690-5afa-9a1c-ea47aa762312', 'מכולה', 'אלונקה', 1, true, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T19:39:29.854000'::timestamptz, '2026-09-14T19:39:29.854000'::timestamptz),
  ('c9328bab-9f3e-556f-9e10-09ffe7ba5730', 'מכולה', 'קסדות', 2, true, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T19:39:15.657000'::timestamptz, '2026-09-14T19:39:15.657000'::timestamptz);

insert into public.withdrawal_requests (id, warehouse, items, requested_by_name, pluga, request_date, expected_return_date, notes, status, approved_by_name, created_by, created_by_id, created_date, updated_date) values
  ('378b7f93-3871-5a78-a76c-3a3b6b0f8b45', 'מכולה', '[{"name": "גריקן", "quantity": 1, "returnable": true}]'::jsonb, 'Jonathan Weizer', 'צין', '2026-09-14', null, null, 'rejected', 'Jonathan Weizer', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T21:07:54.089000'::timestamptz, '2026-09-14T21:08:08.677000'::timestamptz),
  ('59e7140d-754b-5b9c-aaee-9f3a2e52d1aa', 'מכולה', '[{"name": "גריקן", "quantity": 10, "returnable": true}, {"name": "מחבטים", "quantity": 1, "returnable": true}, {"name": "מטף", "quantity": 1, "returnable": true}]'::jsonb, 'Jonathan Weizer', 'בשור', '2026-09-14', '2026-09-16', null, 'pending', null, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T20:39:18.064000'::timestamptz, '2026-09-14T20:39:18.064000'::timestamptz),
  ('8b135723-b84e-5a85-a7fb-08218662264f', 'מכולה', '[{"name": "נפנפים", "quantity": 2, "returnable": true}]'::jsonb, 'Jonathan Weizer', 'פארן', '2026-09-14', '2026-09-15', null, 'pending', null, 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T19:04:07.692000'::timestamptz, '2026-09-14T19:04:07.692000'::timestamptz);

-- equipment_holdings: 0 rows in this export, nothing to insert.

insert into public.equipment_settings (id, responsible_klaf_id, responsible_klaf_name, notification_emails, created_by, created_by_id, created_date, updated_date) values
  ('54e3b8fc-69fa-57ff-97e1-bc0064f31030', null, null, array['noamc1412@gmail.com']::text[], 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T19:17:59.096000'::timestamptz, '2026-09-16T12:02:45.368000'::timestamptz),
  ('349f7989-8c73-5c0e-bc6b-bbf2cae4bee0', null, null, array['joweizer@gmail.com']::text[], 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T19:17:58.308000'::timestamptz, '2026-09-14T19:17:58.308000'::timestamptz);

-- constraints: 0 rows in this export, nothing to insert.

insert into public.access_requests (id, email, full_name, status, assigned_role, pluga, created_by, created_by_id, created_date, updated_date) values
  ('0560d469-8450-5d8a-8492-06a82ec12655', 'leahdemas123@gmail.com', 'טמראלץ', 'approved', 'קלפ', 'צין', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-17T12:56:48.778000'::timestamptz, '2026-09-17T12:58:14.481000'::timestamptz),
  ('c98c96c0-e685-5591-ae74-c9649993a86f', 'ereldekel123321@gmail.com', 'אראל דקל', 'approved', 'קלפ', 'רמון', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-13T16:51:57.032000'::timestamptz, '2026-09-13T16:52:42.004000'::timestamptz),
  ('1d2945f8-269b-579b-b27b-28d27198b69a', 'jojo@gmail.com', 'hhh', 'approved', 'קלפ', 'פארן', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-11T21:47:18'::timestamptz, '2026-09-11T21:47:36.521000'::timestamptz),
  ('117447dc-5f68-5b23-8acc-13264ecfed9e', 'joja@gmail.com', 'joj Bonanza', 'approved', 'קלפ', 'בשור', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-11T21:25:31.870000'::timestamptz, '2026-09-11T21:25:49.313000'::timestamptz),
  ('7ffbaccd-ad0a-5ece-b81b-893278dbc69f', 'joj@gmail.com', 'joj Bonanza', 'approved', 'קלפ', 'צין', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-11T20:38:52.113000'::timestamptz, '2026-09-11T20:39:16.344000'::timestamptz),
  ('dceca21f-eb3c-59de-9102-cc50a03a5f4f', 'test@example.com', 'Test User', 'approved', 'קלפ', 'צין', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-11T19:47:29.961000'::timestamptz, '2026-09-11T20:36:49.266000'::timestamptz);

insert into public.task_completions (id, task_type, task_id, task_field, task_label, task_date, pluga, created_by, created_by_id, created_date, updated_date) values
  ('f9944c7b-2e87-5e4c-8162-567bf4633a8d', 'event', '486b9c63-d49d-525c-9903-47e4a8edcdac', 'responsible', 'זיכוי הגנש', '2026-09-27', 'תמר', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-27T14:15:38.130000'::timestamptz, '2026-09-27T14:15:38.130000'::timestamptz),
  ('ff0beaa1-e90d-5454-bf4d-d50ccf622951', 'direct', 'ed4a6ab6-3fda-5392-a630-359adeefe564', 'ed4a6ab6-3fda-5392-a630-359adeefe564', 'משימה לדוגמה', '2026-09-14', 'בשור', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-14T20:35:47.707000'::timestamptz, '2026-09-14T20:35:47.707000'::timestamptz);

insert into public.gap_updates (id, gap_id, update_type, field, old_value, new_value, text, author_name, created_by, created_by_id, created_date, updated_date) values
  ('4e01ad58-a81e-5f9f-a3e9-15619face8a2', '1fd27232-c31f-5040-8922-92994f536298', 'שינוי סטטוס', 'סטטוס', 'טרם הועלה', 'בטיפול', 'הסטטוס שונה מ-טרם הועלה ל-בטיפול', 'זיו שמיר', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-27T08:05:05.014000'::timestamptz, '2026-09-27T08:05:05.014000'::timestamptz),
  ('ba325f54-9c0b-5bd3-aa00-ea31faa92275', '26e3e1e2-18f5-594e-b5aa-c20e03cba750', 'שינוי סטטוס', 'סטטוס', 'טרם הועלה', 'בטיפול', 'הסטטוס שונה מ-טרם הועלה ל-בטיפול', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-24T12:04:15.068000'::timestamptz, '2026-09-24T12:04:15.068000'::timestamptz),
  ('e9ccda1a-46d0-5f65-b8f0-b228b2ed7ee0', 'acc0dfa0-276a-55ed-be24-59490dcdd004', 'שינוי סטטוס', 'סטטוס', 'בטיפול', 'טופל', 'הסטטוס שונה מ-בטיפול ל-טופל', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-23T10:31:51.032000'::timestamptz, '2026-09-23T10:31:51.032000'::timestamptz),
  ('50adfab0-f713-523f-bc0c-bfed5af6472f', 'b48a580d-0e5f-50d8-8828-85f69f5d6a4e', 'שינוי עדיפות', 'עדיפות', 'גבוה', 'בינוני', 'העדיפות שונתה מ-גבוה ל-בינוני', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-23T10:25:51.683000'::timestamptz, '2026-09-23T10:25:51.683000'::timestamptz),
  ('bf214db9-4bd5-5cdb-af53-65745136e721', 'b48a580d-0e5f-50d8-8828-85f69f5d6a4e', 'שינוי עדיפות', 'עדיפות', 'גבוה', 'בינוני', 'העדיפות שונתה מ-גבוה ל-בינוני', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-23T10:25:44.637000'::timestamptz, '2026-09-23T10:25:44.637000'::timestamptz),
  ('e8bc321b-94bb-51c9-bc79-e9697a628f84', 'b48a580d-0e5f-50d8-8828-85f69f5d6a4e', 'שינוי סטטוס', 'סטטוס', 'טרם הועלה', 'בטיפול', 'הסטטוס שונה מ-טרם הועלה ל-בטיפול', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-23T10:24:52.480000'::timestamptz, '2026-09-23T10:24:52.480000'::timestamptz),
  ('bc3dfacb-69f8-5b9a-92cd-76833dd1b313', '18beb3e0-fed8-5c72-a28d-d8e6fe1d2d58', 'שינוי סטטוס', 'סטטוס', 'טרם הועלה', 'בטיפול', 'הסטטוס שונה מ-טרם הועלה ל-בטיפול', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-23T10:24:01.368000'::timestamptz, '2026-09-23T10:24:01.368000'::timestamptz),
  ('408c3b2d-f1ee-5809-83ec-36aa6d4888bf', '1c626635-b019-58fd-b9f0-01c8881eda7b', 'שינוי סטטוס', 'סטטוס', 'טרם הועלה', 'בטיפול', 'הסטטוס שונה מ-טרם הועלה ל-בטיפול', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-23T10:23:23.927000'::timestamptz, '2026-09-23T10:23:23.927000'::timestamptz),
  ('83deb885-dd7c-5fd6-bda2-5f309b004036', '1de6a54b-1454-589f-ae91-6d22d4ec4451', 'שינוי סטטוס', 'סטטוס', 'טרם הועלה', 'בטיפול', 'הסטטוס שונה מ-טרם הועלה ל-בטיפול', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-23T10:19:07.211000'::timestamptz, '2026-09-23T10:19:07.211000'::timestamptz),
  ('36f3bca7-e85c-50d4-b1a7-1d9765f089ea', '4fb91721-6b67-5a32-895c-92e00eff9e99', 'שינוי סטטוס', 'סטטוס', 'טרם הועלה', 'בטיפול', 'הסטטוס שונה מ-טרם הועלה ל-בטיפול', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-23T10:17:56.690000'::timestamptz, '2026-09-23T10:17:56.690000'::timestamptz),
  ('cabb52ca-402a-5d19-80f1-0dd843cf8ec0', '1a8611b4-96c9-5e74-99a3-00e29cee0d56', 'שינוי סטטוס', 'סטטוס', 'טרם הועלה', 'בטיפול', 'הסטטוס שונה מ-טרם הועלה ל-בטיפול', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-23T10:16:58.701000'::timestamptz, '2026-09-23T10:16:58.701000'::timestamptz),
  ('eb7bb302-1534-5d25-9dfc-9603fb72e4a1', '24e97f7b-a8c1-5bb1-a9f7-361ba11d214b', 'שינוי סטטוס', 'סטטוס', 'טופל', 'בטיפול', 'הסטטוס שונה מ-טופל ל-בטיפול', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-23T10:15:27.650000'::timestamptz, '2026-09-23T10:15:27.650000'::timestamptz),
  ('822061be-c64b-552e-81bc-f8b0799b9632', '24e97f7b-a8c1-5bb1-a9f7-361ba11d214b', 'שינוי סטטוס', 'סטטוס', 'טרם הועלה', 'טופל', 'הסטטוס שונה מ-טרם הועלה ל-טופל', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-23T10:15:15.595000'::timestamptz, '2026-09-23T10:15:15.595000'::timestamptz),
  ('d11e8611-be90-574c-90d8-5c161d929bb2', '1a8611b4-96c9-5e74-99a3-00e29cee0d56', 'שינוי סטטוס', 'סטטוס', 'בטיפול', 'טרם הועלה', 'הסטטוס שונה מ-בטיפול ל-טרם הועלה', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-23T07:50:23.979000'::timestamptz, '2026-09-23T07:50:23.980000'::timestamptz),
  ('3605cc23-b9e0-519a-9873-d0378bb3f4fa', '3a7c1253-7d87-5628-b12f-6e8db5190291', 'שינוי סטטוס', 'סטטוס', 'טרם הועלה', 'טופל', 'הסטטוס שונה מ-טרם הועלה ל-טופל', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-23T07:49:29.743000'::timestamptz, '2026-09-23T07:49:29.743000'::timestamptz),
  ('ae9ecca4-96da-5ec3-b966-36653720ef76', '1de6a54b-1454-589f-ae91-6d22d4ec4451', 'שינוי עדיפות', 'עדיפות', 'בינוני', 'גבוה', 'העדיפות שונתה מ-בינוני ל-גבוה', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-23T07:33:11.635000'::timestamptz, '2026-09-23T07:33:11.635000'::timestamptz),
  ('595d22f2-6790-5165-82b1-93f9e2131f23', 'a6530efa-46f9-5703-b1a8-a5ed903fd805', 'שינוי סטטוס', 'סטטוס', 'בטיפול', 'טופל', 'הסטטוס שונה מ-בטיפול ל-טופל', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-23T07:31:18.829000'::timestamptz, '2026-09-23T07:31:18.829000'::timestamptz),
  ('59470089-561d-5e77-98ff-f84a73771940', '57e66ab8-b380-5655-8431-0304a89e4be3', 'שינוי סטטוס', 'סטטוס', 'בטיפול', 'טופל', 'הסטטוס שונה מ-בטיפול ל-טופל', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-22T18:33:46.598000'::timestamptz, '2026-09-22T18:33:46.598000'::timestamptz),
  ('45089ec3-ecc9-5f49-809b-656506f98aa8', '4a696aa6-85a7-56c7-ba73-b29bab9da6f5', 'שינוי סטטוס', 'סטטוס', 'בטיפול', 'טופל', 'הסטטוס שונה מ-בטיפול ל-טופל', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-22T07:48:55.204000'::timestamptz, '2026-09-22T07:48:55.204000'::timestamptz),
  ('4414b9af-936c-55f3-9600-5a232a021987', '62c04718-0c2e-5d02-9dda-404b71f6d2dc', 'שינוי סטטוס', 'סטטוס', 'בטיפול', 'טופל', 'הסטטוס שונה מ-בטיפול ל-טופל', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-22T07:02:09.946000'::timestamptz, '2026-09-22T07:02:09.946000'::timestamptz),
  ('2f2e5075-683d-5259-9234-4b95b78596dd', '8dfcf6a6-465f-507c-8571-0ba27680fb3f', 'שינוי סטטוס', 'סטטוס', 'בטיפול', 'טופל', 'הסטטוס שונה מ-בטיפול ל-טופל', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-20T07:44:23.060000'::timestamptz, '2026-09-20T07:44:23.060000'::timestamptz),
  ('a805b45b-86e4-5c7a-a37f-186cc1caae15', 'cc0fe401-0d6a-5596-a143-f467208708ff', 'שינוי סטטוס', 'סטטוס', 'בטיפול', 'טופל', 'הסטטוס שונה מ-בטיפול ל-טופל', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-20T06:55:23.626000'::timestamptz, '2026-09-20T06:55:23.626000'::timestamptz),
  ('a154fd0b-c731-5fa4-adda-140e83b19979', 'cef5eea7-d61e-5973-9587-84bc9e9226ea', 'שינוי סטטוס', 'סטטוס', 'בטיפול', 'טופל', 'הסטטוס שונה מ-בטיפול ל-טופל', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-17T12:11:06.883000'::timestamptz, '2026-09-17T12:11:06.883000'::timestamptz),
  ('55e719e2-56fa-5f74-b485-0aa8c2fd3eaf', 'b2cc1193-33f5-54ee-88fb-795bab39e07f', 'שינוי סטטוס', 'סטטוס', 'בטיפול', 'טופל', 'הסטטוס שונה מ-בטיפול ל-טופל', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-17T12:08:06.572000'::timestamptz, '2026-09-17T12:08:06.572000'::timestamptz),
  ('2e3b3a6e-e252-5681-8dcc-e0cbf1a86304', '775137a5-ff5f-5185-92ec-6b2bcfff2c0e', 'שינוי סטטוס', 'סטטוס', 'בטיפול', 'טופל', 'הסטטוס שונה מ-בטיפול ל-טופל', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-17T12:02:55.814000'::timestamptz, '2026-09-17T12:02:55.814000'::timestamptz),
  ('9b317f21-fec1-510a-84d9-793bcfc152ac', 'b9eb5b7d-dbf3-5ae8-9688-1863f21b9109', 'שינוי סטטוס', 'סטטוס', 'בטיפול', 'טופל', 'הסטטוס שונה מ-בטיפול ל-טופל', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-17T12:00:23.397000'::timestamptz, '2026-09-17T12:00:23.397000'::timestamptz),
  ('e9b56506-6b6a-5334-bd85-c9f60d5184b5', '22108fa6-f7b6-5535-96ca-37fda661988b', 'שינוי סטטוס', 'סטטוס', 'בטיפול', 'טופל', 'הסטטוס שונה מ-בטיפול ל-טופל', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-17T11:51:01.224000'::timestamptz, '2026-09-17T11:51:01.224000'::timestamptz),
  ('1edd81b5-46bf-570e-ace4-98247324d023', 'fe164f5f-40bc-5cb0-ac6a-f366c258367f', 'שינוי סטטוס', 'סטטוס', 'טרם הועלה', 'בטיפול', 'הסטטוס שונה מ-טרם הועלה ל-בטיפול', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-17T06:47:29.049000'::timestamptz, '2026-09-17T06:47:29.049000'::timestamptz),
  ('080ec5f5-5efa-5bf2-97bf-29eafc4508ca', '4a696aa6-85a7-56c7-ba73-b29bab9da6f5', 'שינוי עדיפות', 'עדיפות', 'בינוני', 'גבוה', 'העדיפות שונתה מ-בינוני ל-גבוה', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-17T06:37:40.876000'::timestamptz, '2026-09-17T06:37:40.876000'::timestamptz),
  ('73945b86-73e7-5c9e-83ce-e04a11d3e236', '267ffebe-5e7e-5ebf-9f5c-a9aae7af0b7a', 'שינוי עדיפות', 'עדיפות', 'גבוה', 'קריטי', 'העדיפות שונתה מ-גבוה ל-קריטי', 'Tamralech Demas', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-17T06:37:10.439000'::timestamptz, '2026-09-17T06:37:10.439000'::timestamptz),
  ('bc70ec0b-ec8d-544c-a66b-8f96e0b4f173', '775137a5-ff5f-5185-92ec-6b2bcfff2c0e', 'שינוי סטטוס', 'סטטוס', 'טרם הועלה', 'בטיפול', 'הסטטוס שונה מ-טרם הועלה ל-בטיפול', 'Yehonatan Yifrach', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-16T15:37:47.937000'::timestamptz, '2026-09-16T15:37:47.937000'::timestamptz),
  ('70cb18c2-3aff-50a0-8ed1-3057046339cf', '775137a5-ff5f-5185-92ec-6b2bcfff2c0e', 'שינוי סטטוס', 'סטטוס', 'בטיפול', 'טרם הועלה', 'הסטטוס שונה מ-בטיפול ל-טרם הועלה', 'Yehonatan Yifrach', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-16T15:37:47.482000'::timestamptz, '2026-09-16T15:37:47.482000'::timestamptz),
  ('cfb6251a-797f-56de-bf0e-e1de17d04054', '775137a5-ff5f-5185-92ec-6b2bcfff2c0e', 'שינוי סטטוס', 'סטטוס', 'בטיפול', 'טרם הועלה', 'הסטטוס שונה מ-בטיפול ל-טרם הועלה', 'Yehonatan Yifrach', 'יובא מ-Base44', '6292bb9d-89e3-4054-a822-38960eeafa16', '2026-09-16T15:37:46.462000'::timestamptz, '2026-09-16T15:37:46.462000'::timestamptz);

-- recurring_overrides: 0 rows in this export, nothing to insert.

commit;

-- Total rows imported: 133