import React, { useState, useEffect, useCallback, useMemo } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Loader2, Truck, Plus, Trash2, Shield, PackageSearch, Sparkles } from "lucide-react";
import { PLUGOT, PLUGA_COLORS, toDateStr } from "@/lib/constants";
import { cn } from "@/lib/utils";
import { useToast } from "@/components/ui/use-toast";
import { hasPermission, effectivePermissions } from "@/lib/permissions";

const STATUS_LABELS = { "ממתין": "ממתין", "הוזמן": "הוזמן", "בוטל": "בוטל" };

// Standalone page for the playbox_orders delegated permission (see
// src/lib/permissions.js and supabase/migrations/0005_delegated_permissions.sql).
// Org-wide, not per-pluga: whoever is granted this sees every pluga's
// consolidated weekly order requests here, regardless of their role. The
// same permission also gates the stock/reorder-point tab added in
// supabase/migrations/0008_playbox_stock_tracking.sql — no separate
// permission key for it.
export default function Playbox() {
  const [user, setUser] = useState(null);
  const [myPermissions, setMyPermissions] = useState([]);
  const [checking, setChecking] = useState(true);

  useEffect(() => {
    base44.auth.me().then(setUser).catch(() => {});
  }, []);

  useEffect(() => {
    if (!user?.id) return;
    base44.entities.UserPermission.filter({ user_id: user.id })
      .then(setMyPermissions)
      .catch(() => setMyPermissions([]))
      .finally(() => setChecking(false));
  }, [user?.id]);

  if (!user || checking) {
    return (
      <div className="flex justify-center py-20">
        <Loader2 className="w-8 h-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  // Admins hold every delegated permission automatically — see
  // effectivePermissions in src/lib/permissions.js.
  if (!hasPermission(effectivePermissions(myPermissions, user.role), "playbox_orders")) {
    return (
      <div className="text-center py-20 text-muted-foreground space-y-2">
        <Shield className="w-10 h-10 mx-auto opacity-40" />
        <p className="text-sm font-medium">אין לך הרשאה לעמוד זה</p>
        <p className="text-xs">אדמין יכול להעניק הרשאה דרך "ניהול משתמשים ובקשות גישה" → משתמשים</p>
      </div>
    );
  }

  return (
    <div className="max-w-2xl mx-auto px-4 py-6 space-y-4">
      <div className="flex items-center justify-center gap-2">
        <Truck className="w-5 h-5 text-slate-500" />
        <h1 className="text-xl font-bold">פלייבוקס</h1>
      </div>
      <Tabs defaultValue="orders" dir="rtl" className="w-full">
        <TabsList className="w-full grid grid-cols-2">
          <TabsTrigger value="orders">הזמנות</TabsTrigger>
          <TabsTrigger value="stock">מלאי ומעקב חוסרים</TabsTrigger>
        </TabsList>
        <TabsContent value="orders">
          <PlayboxOrders />
        </TabsContent>
        <TabsContent value="stock">
          <PlayboxStock />
        </TabsContent>
      </Tabs>
    </div>
  );
}

// ---------------------------------------------------------------------------
// פלייבוקס — ריכוז בקשות הזמנה מכל הפלוגות (ported from the former
// Delegations.jsx PlayboxTab, unchanged in behavior other than the
// "אוטומטי" badge for orders the stock-gap action generated by itself).
// ---------------------------------------------------------------------------
function PlayboxOrders() {
  const { toast } = useToast();
  const [orders, setOrders] = useState([]);
  const [loading, setLoading] = useState(true);
  const [form, setForm] = useState({ pluga: PLUGOT[0], order_date: toDateStr(new Date()), item: "", quantity: 1, notes: "" });
  const [saving, setSaving] = useState(false);

  const load = useCallback(async () => {
    try {
      const data = await base44.entities.PlayboxOrder.list("-order_date", 200);
      setOrders(data);
    } catch {
      // ignore
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    load();
    const unsubscribe = base44.entities.PlayboxOrder.subscribe(() => load());
    return unsubscribe;
  }, [load]);

  const handleAdd = async () => {
    if (!form.item.trim()) return;
    setSaving(true);
    try {
      await base44.entities.PlayboxOrder.create({
        pluga: form.pluga,
        order_date: form.order_date,
        item: form.item.trim(),
        quantity: Number(form.quantity) || 1,
        notes: form.notes.trim() || null,
        status: "ממתין",
        auto_generated: false,
      });
      setForm((f) => ({ ...f, item: "", quantity: 1, notes: "" }));
      await load();
      toast({ title: "ההזמנה נוספה", duration: 2000 });
    } catch (err) {
      toast({ title: "שגיאה בהוספת ההזמנה", description: err.message, variant: "destructive" });
    } finally {
      setSaving(false);
    }
  };

  const handleStatus = async (order, status) => {
    try {
      await base44.entities.PlayboxOrder.update(order.id, { status });
      await load();
    } catch (err) {
      toast({ title: "שגיאה בעדכון הסטטוס", description: err.message, variant: "destructive" });
    }
  };

  const handleDelete = async (order) => {
    try {
      await base44.entities.PlayboxOrder.delete(order.id);
      await load();
    } catch (err) {
      toast({ title: "שגיאה במחיקה", description: err.message, variant: "destructive" });
    }
  };

  return (
    <div className="space-y-4 pt-2">
      <div className="border rounded-lg p-3 bg-white space-y-2">
        <p className="text-sm font-medium">הוספת בקשת הזמנה</p>
        <div className="grid grid-cols-2 gap-2">
          <Select value={form.pluga} onValueChange={(v) => setForm((f) => ({ ...f, pluga: v }))}>
            <SelectTrigger className="h-9 text-sm"><SelectValue /></SelectTrigger>
            <SelectContent>
              {PLUGOT.map((p) => <SelectItem key={p} value={p}>{p}</SelectItem>)}
            </SelectContent>
          </Select>
          <Input type="date" value={form.order_date} onChange={(e) => setForm((f) => ({ ...f, order_date: e.target.value }))} className="h-9 text-sm" />
        </div>
        <Input placeholder="פריט" value={form.item} onChange={(e) => setForm((f) => ({ ...f, item: e.target.value }))} className="h-9 text-sm" />
        <div className="grid grid-cols-[100px_1fr] gap-2">
          <Input type="number" min="1" value={form.quantity} onChange={(e) => setForm((f) => ({ ...f, quantity: e.target.value }))} className="h-9 text-sm" />
          <Input placeholder="הערות (אופציונלי)" value={form.notes} onChange={(e) => setForm((f) => ({ ...f, notes: e.target.value }))} className="h-9 text-sm" />
        </div>
        <Button size="sm" onClick={handleAdd} disabled={saving || !form.item.trim()} className="w-full gap-1.5">
          <Plus className="w-3.5 h-3.5" />
          הוסף
        </Button>
      </div>

      {loading ? (
        <div className="flex justify-center py-10"><Loader2 className="w-6 h-6 animate-spin text-muted-foreground" /></div>
      ) : orders.length === 0 ? (
        <p className="text-center text-sm text-muted-foreground py-6">אין בקשות הזמנה עדיין</p>
      ) : (
        <div className="space-y-2">
          {orders.map((o) => (
            <div key={o.id} className="border rounded-lg p-3 bg-white flex items-start justify-between gap-2 flex-wrap">
              <div className="min-w-0 space-y-0.5">
                <div className="flex items-center gap-2 flex-wrap">
                  <span className={cn("text-xs px-2 py-0.5 rounded-full font-medium", PLUGA_COLORS[o.pluga]?.light)}>{o.pluga}</span>
                  <span className="text-sm font-medium">{o.item} × {o.quantity}</span>
                  {o.auto_generated && (
                    <span className="text-xs px-2 py-0.5 rounded-full font-medium bg-amber-100 text-amber-700 flex items-center gap-1">
                      <Sparkles className="w-3 h-3" />
                      אוטומטי
                    </span>
                  )}
                </div>
                <p className="text-xs text-muted-foreground">{o.order_date}{o.notes ? ` · ${o.notes}` : ""}</p>
              </div>
              <div className="flex items-center gap-1.5 shrink-0">
                <Select value={o.status} onValueChange={(v) => handleStatus(o, v)}>
                  <SelectTrigger className="h-8 text-xs w-24"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    {Object.keys(STATUS_LABELS).map((s) => <SelectItem key={s} value={s}>{STATUS_LABELS[s]}</SelectItem>)}
                  </SelectContent>
                </Select>
                <Button size="icon" variant="ghost" className="h-8 w-8" onClick={() => handleDelete(o)}>
                  <Trash2 className="w-3.5 h-3.5 text-destructive" />
                </Button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// מלאי ומעקב חוסרים — target vs. current quantity per pluga+item (see
// supabase/migrations/0008_playbox_stock_tracking.sql). Whoever holds
// playbox_orders (plus admins, automatically) sets how much of each item the
// pluga is supposed to have on hand and how much it currently has; the
// "צור הזמנות לחוסרים" button turns every gap into an initial playbox_orders
// row (auto_generated: true) that the same responsible person can then place
// for real from the "הזמנות" tab — it never places anything itself.
// ---------------------------------------------------------------------------
const EMPTY_ITEM_FORM = { item: "", target_quantity: "", current_quantity: "" };

function PlayboxStock() {
  const { toast } = useToast();
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [newItem, setNewItem] = useState(() => Object.fromEntries(PLUGOT.map((p) => [p, EMPTY_ITEM_FORM])));
  const [generating, setGenerating] = useState(false);

  const load = useCallback(async () => {
    try {
      const data = await base44.entities.PlayboxItem.list("item", 500);
      setItems(data);
    } catch {
      // ignore
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    load();
    const unsubscribe = base44.entities.PlayboxItem.subscribe(() => load());
    return unsubscribe;
  }, [load]);

  const itemsByPluga = useMemo(() => {
    const map = Object.fromEntries(PLUGOT.map((p) => [p, []]));
    for (const it of items) {
      if (map[it.pluga]) map[it.pluga].push(it);
    }
    return map;
  }, [items]);

  const gapCount = useMemo(
    () => items.filter((it) => Number(it.current_quantity) < Number(it.target_quantity)).length,
    [items]
  );

  const handleAddItem = async (pluga) => {
    const form = newItem[pluga] || EMPTY_ITEM_FORM;
    const name = form.item.trim();
    if (!name) return;
    try {
      await base44.entities.PlayboxItem.create({
        pluga,
        item: name,
        target_quantity: Number(form.target_quantity) || 0,
        current_quantity: Number(form.current_quantity) || 0,
      });
      setNewItem((n) => ({ ...n, [pluga]: EMPTY_ITEM_FORM }));
      await load();
    } catch (err) {
      toast({ title: "שגיאה בהוספת הפריט", description: err.message, variant: "destructive" });
    }
  };

  const handleUpdateQuantity = async (it, field, value) => {
    const num = value === "" ? 0 : Number(value);
    if (Number.isNaN(num)) return;
    try {
      await base44.entities.PlayboxItem.update(it.id, { [field]: num });
      await load();
    } catch (err) {
      toast({ title: "שגיאה בעדכון", description: err.message, variant: "destructive" });
    }
  };

  const handleDeleteItem = async (it) => {
    try {
      await base44.entities.PlayboxItem.delete(it.id);
      await load();
    } catch (err) {
      toast({ title: "שגיאה במחיקה", description: err.message, variant: "destructive" });
    }
  };

  const handleGenerateGapOrders = async () => {
    setGenerating(true);
    try {
      const gaps = items.filter((it) => Number(it.current_quantity) < Number(it.target_quantity));
      if (gaps.length === 0) {
        toast({ title: "אין חוסרים כרגע", duration: 2000 });
        return;
      }
      // Avoid piling up duplicate auto-generated orders for the same
      // pluga+item while an earlier one is still pending.
      const existingOrders = await base44.entities.PlayboxOrder.list("-order_date", 500);
      const hasPendingAuto = (pluga, item) =>
        existingOrders.some((o) => o.pluga === pluga && o.item === item && o.auto_generated && o.status === "ממתין");

      const today = toDateStr(new Date());
      let created = 0;
      for (const gap of gaps) {
        if (hasPendingAuto(gap.pluga, gap.item)) continue;
        await base44.entities.PlayboxOrder.create({
          pluga: gap.pluga,
          order_date: today,
          item: gap.item,
          quantity: Number(gap.target_quantity) - Number(gap.current_quantity),
          notes: "נוצר אוטומטית ממעקב המלאי",
          status: "ממתין",
          auto_generated: true,
        });
        created += 1;
      }
      if (created === 0) {
        toast({ title: "כל החוסרים כבר הוזמנו", description: "יש הזמנה אוטומטית ממתינה לכל חוסר קיים", duration: 2500 });
      } else {
        toast({ title: `נוצרו ${created} הזמנות לחוסרים`, description: "אפשר לראות ולהזמין בפועל בלשונית \"הזמנות\"", duration: 3000 });
      }
    } catch (err) {
      toast({ title: "שגיאה ביצירת הזמנות", description: err.message, variant: "destructive" });
    } finally {
      setGenerating(false);
    }
  };

  if (loading) {
    return <div className="flex justify-center py-10"><Loader2 className="w-6 h-6 animate-spin text-muted-foreground" /></div>;
  }

  return (
    <div className="space-y-3 pt-2">
      <Button
        onClick={handleGenerateGapOrders}
        disabled={generating}
        className="w-full gap-1.5"
        variant={gapCount > 0 ? "default" : "outline"}
      >
        {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <PackageSearch className="w-4 h-4" />}
        צור הזמנות לחוסרים{gapCount > 0 ? ` (${gapCount})` : ""}
      </Button>

      <div className="grid gap-3 sm:grid-cols-2">
        {PLUGOT.map((pluga) => {
          const color = PLUGA_COLORS[pluga];
          const plugaItems = itemsByPluga[pluga];
          const form = newItem[pluga] || EMPTY_ITEM_FORM;
          return (
            <div key={pluga} className={cn("rounded-xl border-2 p-3 space-y-2", color?.light, color?.border)}>
              <p className="text-sm font-bold">{pluga}</p>
              {plugaItems.length === 0 ? (
                <p className="text-xs text-muted-foreground">לא הוגדרו פריטים</p>
              ) : (
                <div className="space-y-1.5">
                  {plugaItems.map((it) => {
                    const short = Number(it.current_quantity) < Number(it.target_quantity);
                    return (
                      <div key={it.id} className="bg-white rounded-lg p-2 space-y-1.5">
                        <div className="flex items-center justify-between gap-2 flex-wrap">
                          <span className="text-sm font-medium break-words">{it.item}</span>
                          <div className="flex items-center gap-1.5 shrink-0">
                            {short && (
                              <span className="text-xs px-1.5 py-0.5 rounded-full font-medium bg-red-100 text-red-700">
                                חסר {Number(it.target_quantity) - Number(it.current_quantity)}
                              </span>
                            )}
                            <button onClick={() => handleDeleteItem(it)} className="text-muted-foreground hover:text-destructive">
                              <Trash2 className="w-3.5 h-3.5" />
                            </button>
                          </div>
                        </div>
                        <div className="grid grid-cols-2 gap-1.5">
                          <div className="space-y-0.5">
                            <p className="text-[10px] text-muted-foreground">יש כרגע</p>
                            <Input
                              type="number"
                              min="0"
                              defaultValue={it.current_quantity}
                              onBlur={(e) => handleUpdateQuantity(it, "current_quantity", e.target.value)}
                              className="h-8 text-sm"
                            />
                          </div>
                          <div className="space-y-0.5">
                            <p className="text-[10px] text-muted-foreground">צריך שיהיה</p>
                            <Input
                              type="number"
                              min="0"
                              defaultValue={it.target_quantity}
                              onBlur={(e) => handleUpdateQuantity(it, "target_quantity", e.target.value)}
                              className="h-8 text-sm"
                            />
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
              <div className="space-y-1.5 pt-1 border-t border-dashed">
                <Input
                  placeholder="פריט חדש"
                  value={form.item}
                  onChange={(e) => setNewItem((n) => ({ ...n, [pluga]: { ...form, item: e.target.value } }))}
                  className="h-8 text-sm bg-white"
                />
                <div className="grid grid-cols-[1fr_1fr_auto] gap-1.5">
                  <Input
                    type="number"
                    min="0"
                    placeholder="יש"
                    value={form.current_quantity}
                    onChange={(e) => setNewItem((n) => ({ ...n, [pluga]: { ...form, current_quantity: e.target.value } }))}
                    className="h-8 text-sm bg-white"
                  />
                  <Input
                    type="number"
                    min="0"
                    placeholder="צריך"
                    value={form.target_quantity}
                    onChange={(e) => setNewItem((n) => ({ ...n, [pluga]: { ...form, target_quantity: e.target.value } }))}
                    className="h-8 text-sm bg-white"
                  />
                  <Button size="icon" variant="outline" className="h-8 w-8 shrink-0 bg-white" onClick={() => handleAddItem(pluga)}>
                    <Plus className="w-3.5 h-3.5" />
                  </Button>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
